In [2]:
#conda install mlxtend
#conda install mlxtend --channel conda-forge
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
df = pd.read_csv('Retail_Data.csv')
df = df.iloc[:,1:]
df.head()

  Product1   Product2 Product3
0    Bread     Butter    Dairy
1   Nachos     Butter    Dairy
2    Juice        Jam      Egg
3    Juice        Jam      Egg
4    Juice  Vegetable    Salad

In [8]:
df1 = pd.get_dummies(df)
print df1.head()
df1.shape

   Product1_Bread  Product1_Fruits  Product1_Juice  Product1_Nachos  \
0               1                0               0                0
1               0                0               0                1
2               0                0               1                0
3               0                0               1                0
4               0                0               1                0

   Product2_Butter  Product2_Jam  Product2_Salsa  Product2_Vegetable  \
0                1             0               0                   0
1                1             0               0                   0
2                0             1               0                   0
3                0             1               0                   0
4                0             0               0                   1

   Product3_Dairy  Product3_Egg  Product3_Salad
0               1             0               0
1               1             0               0
2               0             1               0
3               0             1               0
4               0             0               1

(2000, 11)

In [9]:
#encontrando regras com no m√≠nimo 5% de suporte
frequent_items = apriori(df1, min_support=0.05, use_colnames=True)

In [10]:
#encontrar regras com lift maior que 1
rules = association_rules(frequent_items, metric='lift', min_threshold=1)
type(rules)
rules.shape
rules

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(Product2_Jam, Product3_Dairy)",(Product1_Bread),0.0720,0.3510,0.0720,1.000000,2.849003,0.046728,inf
1,"(Product2_Jam, Product1_Bread)",(Product3_Dairy),0.1280,0.2030,0.0720,0.562500,2.770936,0.046016,1.821714
2,"(Product3_Dairy, Product1_Bread)",(Product2_Jam),0.1005,0.3410,0.0720,0.716418,2.100932,0.037729,2.323842
3,(Product2_Jam),"(Product3_Dairy, Product1_Bread)",0.3410,0.1005,0.0720,0.211144,2.100932,0.037729,1.140258
4,(Product3_Dairy),"(Product2_Jam, Product1_Bread)",0.2030,0.1280,0.0720,0.354680,2.770936,0.046016,1.351267
5,(Product1_Bread),"(Product2_Jam, Product3_Dairy)",0.3510,0.0720,0.0720,0.205128,2.849003,0.046728,1.167484
6,(Product2_Jam),(Product1_Bread),0.3410,0.3510,0.1280,0.375367,1.069420,0.008309,1.039009
7,(Product1_Bread),(Product2_Jam),0.3510,0.3410,0.1280,0.364672,1.069420,0.008309,1.037260
8,"(Product1_Nachos, Product2_Salsa)",(Product3_Dairy),0.1880,0.2030,0.0705,0.375000,1.847291,0.032336,1.275200
9,"(Product1_Nachos, Product3_Dairy)",(Product2_Salsa),0.1025,0.1965,0.0705,0.687805,3.500279,0.050359,2.573711
10,"(Product2_Salsa, Product3_Dairy)",(Product1_Nachos),0.0790,0.2200,0.0705,0.892405,4.056387,0.053120,7.249412
11,(Product1_Nachos),"(Product2_Salsa, Product3_Dairy)",0.2200,0.0790,0.0705,0.320455,4.056387,0.053120,1.355318
12,(Product2_Salsa),"(Product1_Nachos, Product3_Dairy)",0.1965,0.1025,0.0705,0.358779,3.500279,0.050359,1.399673
13,(Product3_Dairy),"(Product1_Nachos, Product2_Salsa)",0.2030,0.1880,0.0705,0.347291,1.847291,0.032336,1.244045
14,(Product1_Juice),(Product3_Egg),0.2465,0.5760,0.2080,0.843813,1.464954,0.066016,2.714701
15,(Product3_Egg),(Product1_Juice),0.5760,0.2465,0.2080,0.361111,1.464954,0.066016,1.179391
16,(Product2_Salsa),(Product3_Dairy),0.1965,0.2030,0.0790,0.402036,1.980471,0.039110,1.332855
17,(Product3_Dairy),(Product2_Salsa),0.2030,0.1965,0.0790,0.389163,1.980471,0.039110,1.315407
18,(Product1_Nachos),(Product2_Salsa),0.2200,0.1965,0.1880,0.854545,4.348832,0.144770,5.524062
19,(Product2_Salsa),(Product1_Nachos),0.1965,0.2200,0.1880,0.956743,4.348832,0.144770,18.031765
20,(Product1_Fruits),(Product3_Salad),0.1825,0.2210,0.1825,1.000000,4.524887,0.142168,inf
21,(Product3_Salad),(Product1_Fruits),0.2210,0.1825,0.1825,0.825792,4.524887,0.142168,4.692662
22,(Product2_Butter),(Product3_Egg),0.2465,0.5760,0.1945,0.789047,1.369873,0.052516,2.009923
23,(Product3_Egg),(Product2_Butter),0.5760,0.2465,0.1945,0.337674,1.369873,0.052516,1.137657
24,(Product2_Butter),(Product1_Bread),0.2465,0.3510,0.2145,0.870183,2.479153,0.127978,4.999328
25,(Product1_Bread),(Product2_Butter),0.3510,0.2465,0.2145,0.611111,2.479153,0.127978,1.937571
26,(Product2_Salsa),(Product3_Egg),0.1965,0.5760,0.1175,0.597964,1.038133,0.004316,1.054633
27,(Product3_Egg),(Product2_Salsa),0.5760,0.1965,0.1175,0.203993,1.038133,0.004316,1.009413
28,(Product3_Egg),(Product1_Bread),0.5760,0.3510,0.2505,0.434896,1.239019,0.048324,1.148461
29,(Product1_Bread),(Product3_Egg),0.3510,0.5760,0.2505,0.713675,1.239019,0.048324,1.480836
...,...,...,...,...,...,...,...,...,...
40,(Product1_Fruits),"(Product2_Vegetable, Product3_Salad)",0.1825,0.2090,0.1705,0.934247,4.470079,0.132358,12.029792
41,(Product2_Vegetable),"(Product1_Fruits, Product3_Salad)",0.2160,0.1825,0.1705,0.789352,4.325216,0.131080,3.880879
42,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,0.094411,inf
43,"(Product3_Egg, Product2_Salsa)",(Product1_Nachos),0.1175,0.2200,0.1175,1.000000,4.545455,0.091650,inf
44,"(Product1_Nachos, Product2_Salsa)",(Product3_Egg),0.1880,0.5760,0.1175,0.625000,1.085069,0.009212,1.130667
45,(Product3_Egg),"(Product1_Nachos, Product2_Salsa)",0.5760,0.1880,0.1175,0.203993,1.085069,0.009212,1.020092
46,(Product1_Nachos),"(Product3_Egg, Product2_Salsa)",0.2200,0.1175,0.1175,0.534091,4.545455,0.091650,1.894146
47,(Product2_Salsa),"(Product3_Egg, Product1_Nachos)",0.1965,0.1175,0.1175,0.597964,5.089059,0.094411,2.195079
48,(Product3_Dairy),(Product1_Bread),0.2030,0.3510,0.1005,0.495074,1.410467,0.029247,1.285337
49,(Product1_Bread),(Product3_Dairy),0.3510,0.2030,0.1005,0.286325,1.410467,0.029247,1.116754
50,"(Product2_Butter, Product3_Egg)",(Product1_Bread),0.1945,0.3510,0.1945,1.000000,2.849003,0.126231,inf
51,"(Product2_Butter, Product1_Bread)",(Product3_Egg),0.2145,0.5760,0.1945,0.906760,1.574236,0.070948,4.547400
52,"(Product3_Egg, Product1_Bread)",(Product2_Butter),0.2505,0.2465,0.1945,0.776447,3.149887,0.132752,3.370567
53,(Product2_Butter),"(Product3_Egg, Product1_Bread)",0.2465,0.2505,0.1945,0.789047,3.149887,0.132752,3.552918
54,(Product3_Egg),"(Product2_Butter, Product1_Bread)",0.5760,0.2145,0.1945,0.337674,1.574236,0.070948,1.185971
55,(Product1_Bread),"(Product2_Butter, Product3_Egg)",0.3510,0.1945,0.1945,0.554131,2.849003,0.126231,1.806585
56,(Product2_Butter),(Product3_Dairy),0.2465,0.2030,0.0520,0.210953,1.039179,0.001960,1.010080
57,(Product3_Dairy),(Product2_Butter),0.2030,0.2465,0.0520,0.256158,1.039179,0.001960,1.012983
58,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,0.161264,24.037714
59,(Product3_Salad),(Product2_Vegetable),0.2210,0.2160,0.2090,0.945701,4.378247,0.161264,14.438667
60,(Product3_Egg),(Product2_Jam),0.5760,0.3410,0.2570,0.446181,1.308447,0.060584,1.189918
61,(Product2_Jam),(Product3_Egg),0.3410,0.5760,0.2570,0.753666,1.308447,0.060584,1.721238
62,(Product1_Nachos),(Product3_Dairy),0.2200,0.2030,0.1025,0.465909,2.295119,0.057840,1.492255
63,(Product3_Dairy),(Product1_Nachos),0.2030,0.2200,0.1025,0.504926,2.295119,0.057840,1.575522
64,"(Product1_Juice, Product3_Egg)",(Product2_Jam),0.2080,0.3410,0.2010,0.966346,2.833860,0.130072,19.581714
65,"(Product1_Juice, Product2_Jam)",(Product3_Egg),0.2010,0.5760,0.2010,1.000000,1.736111,0.085224,inf
66,"(Product3_Egg, Product2_Jam)",(Product1_Juice),0.2570,0.2465,0.2010,0.782101,3.172824,0.137650,3.458027
67,(Product1_Juice),"(Product3_Egg, Product2_Jam)",0.2465,0.2570,0.2010,0.815416,3.172824,0.137650,4.025264
68,(Product3_Egg),"(Product1_Juice, Product2_Jam)",0.5760,0.2010,0.2010,0.348958,1.736111,0.085224,1.227264
69,(Product2_Jam),"(Product1_Juice, Product3_Egg)",0.3410,0.2080,0.2010,0.589443,2.833860,0.130072,1.929086

In [11]:
#10 primeiras regras com maior suporte
rules.sort_values('support', ascending= False).head(10)

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
60,(Product3_Egg),(Product2_Jam),0.5760,0.3410,0.2570,0.446181,1.308447,0.060584,1.189918
61,(Product2_Jam),(Product3_Egg),0.3410,0.5760,0.2570,0.753666,1.308447,0.060584,1.721238
28,(Product3_Egg),(Product1_Bread),0.5760,0.3510,0.2505,0.434896,1.239019,0.048324,1.148461
29,(Product1_Bread),(Product3_Egg),0.3510,0.5760,0.2505,0.713675,1.239019,0.048324,1.480836
24,(Product2_Butter),(Product1_Bread),0.2465,0.3510,0.2145,0.870183,2.479153,0.127978,4.999328
25,(Product1_Bread),(Product2_Butter),0.3510,0.2465,0.2145,0.611111,2.479153,0.127978,1.937571
59,(Product3_Salad),(Product2_Vegetable),0.2210,0.2160,0.2090,0.945701,4.378247,0.161264,14.438667
58,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,0.161264,24.037714
14,(Product1_Juice),(Product3_Egg),0.2465,0.5760,0.2080,0.843813,1.464954,0.066016,2.714701
15,(Product3_Egg),(Product1_Juice),0.5760,0.2465,0.2080,0.361111,1.464954,0.066016,1.179391

In [12]:
#10 primeiras regras com maior confianca
rules.sort_values('confidence', ascending= False).head(10)

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(Product2_Jam, Product3_Dairy)",(Product1_Bread),0.0720,0.3510,0.0720,1.000000,2.849003,0.046728,inf
42,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,0.094411,inf
43,"(Product3_Egg, Product2_Salsa)",(Product1_Nachos),0.1175,0.2200,0.1175,1.000000,4.545455,0.091650,inf
20,(Product1_Fruits),(Product3_Salad),0.1825,0.2210,0.1825,1.000000,4.524887,0.142168,inf
65,"(Product1_Juice, Product2_Jam)",(Product3_Egg),0.2010,0.5760,0.2010,1.000000,1.736111,0.085224,inf
38,"(Product1_Fruits, Product2_Vegetable)",(Product3_Salad),0.1705,0.2210,0.1705,1.000000,4.524887,0.132820,inf
50,"(Product2_Butter, Product3_Egg)",(Product1_Bread),0.1945,0.3510,0.1945,1.000000,2.849003,0.126231,inf
58,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,0.161264,24.037714
64,"(Product1_Juice, Product3_Egg)",(Product2_Jam),0.2080,0.3410,0.2010,0.966346,2.833860,0.130072,19.581714
19,(Product2_Salsa),(Product1_Nachos),0.1965,0.2200,0.1880,0.956743,4.348832,0.144770,18.031765

In [13]:
#10 primeiras regras com maior lift
rules.sort_values('lift', ascending= False).head(10)

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
47,(Product2_Salsa),"(Product3_Egg, Product1_Nachos)",0.1965,0.1175,0.1175,0.597964,5.089059,0.094411,2.195079
42,"(Product3_Egg, Product1_Nachos)",(Product2_Salsa),0.1175,0.1965,0.1175,1.000000,5.089059,0.094411,inf
43,"(Product3_Egg, Product2_Salsa)",(Product1_Nachos),0.1175,0.2200,0.1175,1.000000,4.545455,0.091650,inf
46,(Product1_Nachos),"(Product3_Egg, Product2_Salsa)",0.2200,0.1175,0.1175,0.534091,4.545455,0.091650,1.894146
38,"(Product1_Fruits, Product2_Vegetable)",(Product3_Salad),0.1705,0.2210,0.1705,1.000000,4.524887,0.132820,inf
21,(Product3_Salad),(Product1_Fruits),0.2210,0.1825,0.1825,0.825792,4.524887,0.142168,4.692662
20,(Product1_Fruits),(Product3_Salad),0.1825,0.2210,0.1825,1.000000,4.524887,0.142168,inf
39,(Product3_Salad),"(Product1_Fruits, Product2_Vegetable)",0.2210,0.1705,0.1705,0.771493,4.524887,0.132820,3.630089
40,(Product1_Fruits),"(Product2_Vegetable, Product3_Salad)",0.1825,0.2090,0.1705,0.934247,4.470079,0.132358,12.029792
37,"(Product2_Vegetable, Product3_Salad)",(Product1_Fruits),0.2090,0.1825,0.1705,0.815789,4.470079,0.132358,4.437857

In [15]:
#selecionando regras com lift maior que 2, confianca maior que 0.6 e suporte maior que 0.2
rules[(rules['lift'] >= 2) & (rules['confidence'] >= 0.6) & (rules['support'] >= 0.2 )]

,antecedants,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
24,(Product2_Butter),(Product1_Bread),0.2465,0.3510,0.2145,0.870183,2.479153,0.127978,4.999328
25,(Product1_Bread),(Product2_Butter),0.3510,0.2465,0.2145,0.611111,2.479153,0.127978,1.937571
34,(Product1_Juice),(Product2_Jam),0.2465,0.3410,0.2010,0.815416,2.391249,0.116944,3.570187
58,(Product2_Vegetable),(Product3_Salad),0.2160,0.2210,0.2090,0.967593,4.378247,0.161264,24.037714
59,(Product3_Salad),(Product2_Vegetable),0.2210,0.2160,0.2090,0.945701,4.378247,0.161264,14.438667
64,"(Product1_Juice, Product3_Egg)",(Product2_Jam),0.2080,0.3410,0.2010,0.966346,2.833860,0.130072,19.581714
66,"(Product3_Egg, Product2_Jam)",(Product1_Juice),0.2570,0.2465,0.2010,0.782101,3.172824,0.137650,3.458027
67,(Product1_Juice),"(Product3_Egg, Product2_Jam)",0.2465,0.2570,0.2010,0.815416,3.172824,0.137650,4.025264

In [ ]:
# Exerc√≠cio proposto
#Encontrar para um √∫nico pa√≠s regras usando apriori, 
# com medidas de suporte, confianca e lift e dizer quais poss√≠veis melhores valores para tais medidas

#dados do dataset em https://archive.ics.uci.edu/ml/datasets/online+retail